### ISSUE TITLE
Panic in Aggregation

### ISSUE THREAD

**Issue by brancz** [polarsignals/arcticdb#26]
```
panic: runtime error: index out of range [0] with length 0

goroutine 51647 [running]:
github.com/polarsignals/arcticdb/query/physicalplan.(*HashAggregate).Callback(0x1400cd3e2a0, {0x1089fb7f8, 0x14019cbf980})
        /Users/brancz/src/github.com/polarsignals/arcticdb/query/physicalplan/aggregate.go:220 +0x6e8
github.com/polarsignals/arcticdb/query/physicalplan.(*PredicateFilter).Callback(0x14019b9eb70, {0x1089fb7f8?, 0x14019cbf860?})
        /Users/brancz/src/github.com/polarsignals/arcticdb/query/physicalplan/filter.go:181 +0xbc
github.com/polarsignals/arcticdb.(*Table).Iterator(0x1400a2ea200?, {0x1089dcaf0, 0x10a4c5600}, {0x1403bde2900, 0x8, 0x8}, {0x1089ec1e8, 0x14019b54a80}, {0x0, 0x0, ...}, ...)
        /Users/brancz/src/github.com/polarsignals/arcticdb/table.go:231 +0x16c
github.com/polarsignals/arcticdb/query/physicalplan.(*TableScan).Execute(0x1400d9d0ba0, {0x1089dcaf0, 0x10a4c5600})
        /Users/brancz/src/github.com/polarsignals/arcticdb/query/physicalplan/physicalplan.go:71 +0x100
github.com/polarsignals/arcticdb/query/physicalplan.(*OutputPlan).Execute(...)
        /Users/brancz/src/github.com/polarsignals/arcticdb/query/physicalplan/physicalplan.go:57
github.com/polarsignals/arcticdb/query.LocalQueryBuilder.Execute({{0x1089dcaf0?, 0x10a4c5600?}, {0x1400a2ea240?}}, 0x14015e39870)
        /Users/brancz/src/github.com/polarsignals/arcticdb/query/engine.go:113 +0x138
github.com/parca-dev/parca/pkg/query.(*ColumnQueryAPI).findSingle(0x140033d8320, {0x1089ea968?, 0x14019af0240?}, {0x1400d9d09e0?, 0x3, 0x4}, {0x1400a281e00?, 0x0?, 0x0?})
        /Users/brancz/src/github.com/parca-dev/parca/pkg/query/columnquery.go:426 +0x964
github.com/parca-dev/parca/pkg/query.(*ColumnQueryAPI).selectSingle(0x140033d8320, {0x1089ea968, 0x14019af0240}, 0x1400a281e00)
        /Users/brancz/src/github.com/parca-dev/parca/pkg/query/columnquery.go:383 +0x168
github.com/parca-dev/parca/pkg/query.(*ColumnQueryAPI).singleRequest(0x14008c7ae60?, {0x1089ea968, 0x14019af0240}, 0x6?, 0xb93338?)
        /Users/brancz/src/github.com/parca-dev/parca/pkg/query/columnquery.go:368 +0x30
github.com/parca-dev/parca/pkg/query.(*ColumnQueryAPI).Query(0xa41?, {0x1089ea968, 0x14019af0240}, 0x14008c7ae60)
        /Users/brancz/src/github.com/parca-dev/parca/pkg/query/columnquery.go:317 +0x80
github.com/parca-dev/parca/gen/proto/go/parca/query/v1alpha1._QueryService_Query_Handler.func1({0x1089ea968, 0x14019af0240}, {0x10885e580?, 0x14008c7ae60})
        /Users/brancz/src/github.com/parca-dev/parca/gen/proto/go/parca/query/v1alpha1/query_vtproto.pb.go:183 +0x78
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x1089ea968, 0x14019af0240}, {0x10885e580, 0x14008c7ae60}, 0x0?, 0x14014b76b88)
        /Users/brancz/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/interceptors/server.go:22 +0x158
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x1089ea968?, 0x14019af0240?}, {0x10885e580?, 0x14008c7ae60?})
        /Users/brancz/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x40
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x1089ea968, 0x14019af0240}, {0x10885e580, 0x14008c7ae60}, 0x0?, 0x1400d9d0820)
        /Users/brancz/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x78
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x1089ea968?, 0x14019af0240?}, {0x10885e580?, 0x14008c7ae60?})
        /Users/brancz/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x40
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x1089ea968, 0x14019aa7b00}, {0x10885e580, 0x14008c7ae60}, 0x1400d9d0800, 0x1400d9d0840)
        /Users/brancz/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.30.0/interceptor.go:325 +0x4ec
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x1089ea968?, 0x14019aa7b00?}, {0x10885e580?, 0x14008c7ae60?})
        /Users/brancz/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x40
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x1089ea968, 0x14019aa7b00}, {0x10885e580, 0x14008c7ae60}, 0x14000377ad8?, 0x10544c198?)
        /Users/brancz/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbc
github.com/parca-dev/parca/gen/proto/go/parca/query/v1alpha1._QueryService_Query_Handler({0x108806f40?, 0x140033d8320}, {0x1089ea968, 0x14019aa7b00}, 0x1400b83ba40, 0x140033c44b0)
        /Users/brancz/src/github.com/parca-dev/parca/gen/proto/go/parca/query/v1alpha1/query_vtproto.pb.go:185 +0x13c
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000e9dc00, {0x1089f8f10, 0x1400ec5a510}, 0x1400a28e360, 0x140033c4750, 0x10a4671d8, 0x0)
        /Users/brancz/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xb3c
google.golang.org/grpc.(*Server).handleStream(0x14000e9dc00, {0x1089f8f10, 0x1400ec5a510}, 0x1400a28e360, 0x0)
        /Users/brancz/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /Users/brancz/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/brancz/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x298
```

**Comment by brancz** [comment]
I believe this is closed by #27
